services:
  my-backend-test:
    container_name: mounttest
    image: my-backend-test
    network_mode: fsscan-net
    ports:
    - 50051:50051/tcp
    volumes:
    - /home/drossi/myTest/data:/home/drossi/myTest/data:rw
  my-frontend-test:
    container_name: mounttest2
    image: my-frontend-test
    network_mode: fsscan-net
    ports:
    - 8082:8082/tcp
  my-fsscan-test:
    container_name: mounttest1
    image: my-fsscan-test
    network_mode: fsscan-net
    volumes:
    - /home/drossi/myTest/data:/home/drossi/myTest/data:rw
version: '3.0'

