version: "3"

services:
  my-backend-test:
      network_mode: fsscan-net
      ports:
      - '${GRPC_SERVER_PORT}:${GRPC_SERVER_PORT}'
      container_name: mounttest
      image: my-backend-test
      volumes:
      - /home/drossi/myTest/data:/home/drossi/myTest/data

  my-fsscan-test:
      network_mode: fsscan-net
      container_name: mounttest1
      image: my-fsscan-test
      volumes:
      - /home/drossi/myTest/data:/home/drossi/myTest/data

  my-frontend-test:
      network_mode: fsscan-net
      ports:
      - '${HTTP_FRONTEND_PORT}:${HTTP_FRONTEND_PORT}'
      container_name: mounttest2
      image: my-frontend-test