apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
 name: my-frontend-hpa
 namespace: daniele
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: my-frontend-test
 minReplicas: 1
 maxReplicas: 4
 targetCPUUtilizationPercentage: 5