apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-frontend-test
  namespace: daniele
spec:
  replicas: 4
  selector:
    matchLabels:
      app: my-frontend-test
  template:
    metadata:
      labels:
        app: my-frontend-test
    spec:
      containers:
      - name: my-frontend-test
        image: k8s-master.local:5000/daniele-my-frontend-test:latest
        env:
        - name: USERNAME
          valueFrom:
            secretKeyRef:
              name: scanfile-secret
              key: username
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: scanfile-secret
              key: password
        - name: USERNAME2
          valueFrom:
            secretKeyRef:
              name: scanfile-secret
              key: username2
        - name: PASSWORD2
          valueFrom:
            secretKeyRef:
              name: scanfile-secret
              key: password2
        - name: USERNAME3
          valueFrom:
            secretKeyRef:
              name: scanfile-secret
              key: username3
        - name: PASSWORD3
          valueFrom:
            secretKeyRef:
              name: scanfile-secret
              key: password3
        ports:
        - containerPort: ${HTTP_FRONTEND_PORT}
        - containerPort: ${GRPC_SERVER_PORT}
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        envFrom:
        - configMapRef:
            name: my-scanfile-config
