apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-fsscan-test
  namespace: daniele
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-fsscan-test
  template:
    metadata:
      labels:
        app: my-fsscan-test
    spec:
      # nodeName: k8s-worker3
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - k8s-worker1.local
      containers:
      - name: my-fsscan-test
        image: k8s-master.local:5000/daniele-my-fsscan-test:latest
        ports:
        - containerPort: ${GRPC_SERVER_PORT}
        volumeMounts:
          - mountPath: /app/myData/scanfile
            name: my-fsscan-pv-data
          - mountPath: /app/data
            name: my-fsscan-pv-env
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        envFrom:
        - configMapRef:
            name: my-scanfile-config
      volumes:
        - name: my-fsscan-pv-data
          persistentVolumeClaim:
            claimName: scanfile-data-daniele-pvclaim
        - name: my-fsscan-pv-env
          persistentVolumeClaim:
            claimName: scanfile-env-daniele-pvclaim
        
