apiVersion: v1
kind: ConfigMap
metadata:
  name: my-scanfile-config
  namespace: daniele
data:
  GRPC_SERVER_PORT: "50051"
  HTTP_FRONTEND_PORT: "8082"
  HTTP_FRONTEND_NODEPORT: "30002"
  SCANFILE_BASEDIR: "/home/daniele/Daniele/"
