// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.9
// source: file_scan_stat.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TriggerBackend struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Trigger uint32 `protobuf:"varint,1,opt,name=trigger,proto3" json:"trigger,omitempty"`
}

func (x *TriggerBackend) Reset() {
	*x = TriggerBackend{}
	if protoimpl.UnsafeEnabled {
		mi := &file_file_scan_stat_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TriggerBackend) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerBackend) ProtoMessage() {}

func (x *TriggerBackend) ProtoReflect() protoreflect.Message {
	mi := &file_file_scan_stat_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerBackend.ProtoReflect.Descriptor instead.
func (*TriggerBackend) Descriptor() ([]byte, []int) {
	return file_file_scan_stat_proto_rawDescGZIP(), []int{0}
}

func (x *TriggerBackend) GetTrigger() uint32 {
	if x != nil {
		return x.Trigger
	}
	return 0
}

type TriggerBackendRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TriggerRes uint32 `protobuf:"varint,1,opt,name=trigger_res,json=triggerRes,proto3" json:"trigger_res,omitempty"`
}

func (x *TriggerBackendRes) Reset() {
	*x = TriggerBackendRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_file_scan_stat_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TriggerBackendRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerBackendRes) ProtoMessage() {}

func (x *TriggerBackendRes) ProtoReflect() protoreflect.Message {
	mi := &file_file_scan_stat_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerBackendRes.ProtoReflect.Descriptor instead.
func (*TriggerBackendRes) Descriptor() ([]byte, []int) {
	return file_file_scan_stat_proto_rawDescGZIP(), []int{1}
}

func (x *TriggerBackendRes) GetTriggerRes() uint32 {
	if x != nil {
		return x.TriggerRes
	}
	return 0
}

type Word struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	W string `protobuf:"bytes,1,opt,name=w,proto3" json:"w,omitempty"`  // word
	F uint32 `protobuf:"varint,2,opt,name=f,proto3" json:"f,omitempty"` // word frequency in a File
}

func (x *Word) Reset() {
	*x = Word{}
	if protoimpl.UnsafeEnabled {
		mi := &file_file_scan_stat_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Word) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Word) ProtoMessage() {}

func (x *Word) ProtoReflect() protoreflect.Message {
	mi := &file_file_scan_stat_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Word.ProtoReflect.Descriptor instead.
func (*Word) Descriptor() ([]byte, []int) {
	return file_file_scan_stat_proto_rawDescGZIP(), []int{2}
}

func (x *Word) GetW() string {
	if x != nil {
		return x.W
	}
	return ""
}

func (x *Word) GetF() uint32 {
	if x != nil {
		return x.F
	}
	return 0
}

type File struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PathName string `protobuf:"bytes,1,opt,name=path_name,json=pathName,proto3" json:"path_name,omitempty"`
	Language string `protobuf:"bytes,2,opt,name=language,proto3" json:"language,omitempty"`
	NumWords uint32 `protobuf:"varint,3,opt,name=num_words,json=numWords,proto3" json:"num_words,omitempty"`
}

func (x *File) Reset() {
	*x = File{}
	if protoimpl.UnsafeEnabled {
		mi := &file_file_scan_stat_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *File) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*File) ProtoMessage() {}

func (x *File) ProtoReflect() protoreflect.Message {
	mi := &file_file_scan_stat_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use File.ProtoReflect.Descriptor instead.
func (*File) Descriptor() ([]byte, []int) {
	return file_file_scan_stat_proto_rawDescGZIP(), []int{3}
}

func (x *File) GetPathName() string {
	if x != nil {
		return x.PathName
	}
	return ""
}

func (x *File) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *File) GetNumWords() uint32 {
	if x != nil {
		return x.NumWords
	}
	return 0
}

type FilesStats struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	File  *File    `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	Words []*Word  `protobuf:"bytes,2,rep,name=words,proto3" json:"words,omitempty"`
	List  []string `protobuf:"bytes,3,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *FilesStats) Reset() {
	*x = FilesStats{}
	if protoimpl.UnsafeEnabled {
		mi := &file_file_scan_stat_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FilesStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilesStats) ProtoMessage() {}

func (x *FilesStats) ProtoReflect() protoreflect.Message {
	mi := &file_file_scan_stat_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilesStats.ProtoReflect.Descriptor instead.
func (*FilesStats) Descriptor() ([]byte, []int) {
	return file_file_scan_stat_proto_rawDescGZIP(), []int{4}
}

func (x *FilesStats) GetFile() *File {
	if x != nil {
		return x.File
	}
	return nil
}

func (x *FilesStats) GetWords() []*Word {
	if x != nil {
		return x.Words
	}
	return nil
}

func (x *FilesStats) GetList() []string {
	if x != nil {
		return x.List
	}
	return nil
}

type FsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Lang string `protobuf:"bytes,1,opt,name=lang,proto3" json:"lang,omitempty"`
	Num  uint32 `protobuf:"varint,2,opt,name=num,proto3" json:"num,omitempty"`
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	List string `protobuf:"bytes,4,opt,name=list,proto3" json:"list,omitempty"`
}

func (x *FsRequest) Reset() {
	*x = FsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_file_scan_stat_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FsRequest) ProtoMessage() {}

func (x *FsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_file_scan_stat_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FsRequest.ProtoReflect.Descriptor instead.
func (*FsRequest) Descriptor() ([]byte, []int) {
	return file_file_scan_stat_proto_rawDescGZIP(), []int{5}
}

func (x *FsRequest) GetLang() string {
	if x != nil {
		return x.Lang
	}
	return ""
}

func (x *FsRequest) GetNum() uint32 {
	if x != nil {
		return x.Num
	}
	return 0
}

func (x *FsRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FsRequest) GetList() string {
	if x != nil {
		return x.List
	}
	return ""
}

var File_file_scan_stat_proto protoreflect.FileDescriptor

var file_file_scan_stat_proto_rawDesc = []byte{
	0x0a, 0x14, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x73, 0x63, 0x61, 0x6e, 0x5f, 0x73, 0x74, 0x61, 0x74,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x63, 0x61, 0x6e,
	0x73, 0x74, 0x61, 0x74, 0x22, 0x2a, 0x0a, 0x0e, 0x54, 0x72, 0x69, 0x67, 0x67, 0x65, 0x72, 0x42,
	0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x74, 0x72, 0x69, 0x67, 0x67, 0x65,
	0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x74, 0x72, 0x69, 0x67, 0x67, 0x65, 0x72,
	0x22, 0x34, 0x0a, 0x11, 0x54, 0x72, 0x69, 0x67, 0x67, 0x65, 0x72, 0x42, 0x61, 0x63, 0x6b, 0x65,
	0x6e, 0x64, 0x52, 0x65, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x74, 0x72, 0x69, 0x67, 0x67, 0x65, 0x72,
	0x5f, 0x72, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x74, 0x72, 0x69, 0x67,
	0x67, 0x65, 0x72, 0x52, 0x65, 0x73, 0x22, 0x22, 0x0a, 0x04, 0x57, 0x6f, 0x72, 0x64, 0x12, 0x0c,
	0x0a, 0x01, 0x77, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x01, 0x77, 0x12, 0x0c, 0x0a, 0x01,
	0x66, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x01, 0x66, 0x22, 0x5c, 0x0a, 0x04, 0x46, 0x69,
	0x6c, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x61, 0x74, 0x68, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x74, 0x68, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x1a, 0x0a, 0x08, 0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x6e,
	0x75, 0x6d, 0x5f, 0x77, 0x6f, 0x72, 0x64, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08,
	0x6e, 0x75, 0x6d, 0x57, 0x6f, 0x72, 0x64, 0x73, 0x22, 0x72, 0x0a, 0x0a, 0x46, 0x69, 0x6c, 0x65,
	0x73, 0x53, 0x74, 0x61, 0x74, 0x73, 0x12, 0x26, 0x0a, 0x04, 0x66, 0x69, 0x6c, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x63, 0x61, 0x6e, 0x73,
	0x74, 0x61, 0x74, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x04, 0x66, 0x69, 0x6c, 0x65, 0x12, 0x28,
	0x0a, 0x05, 0x77, 0x6f, 0x72, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e,
	0x66, 0x69, 0x6c, 0x65, 0x73, 0x63, 0x61, 0x6e, 0x73, 0x74, 0x61, 0x74, 0x2e, 0x57, 0x6f, 0x72,
	0x64, 0x52, 0x05, 0x77, 0x6f, 0x72, 0x64, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74,
	0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x22, 0x59, 0x0a, 0x09,
	0x46, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x61, 0x6e,
	0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6c, 0x61, 0x6e, 0x67, 0x12, 0x10, 0x0a,
	0x03, 0x6e, 0x75, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x6e, 0x75, 0x6d, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x32, 0xa5, 0x01, 0x0a, 0x0f, 0x53, 0x63, 0x61, 0x6e,
	0x53, 0x74, 0x61, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x46, 0x0a, 0x0d, 0x47,
	0x65, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x53, 0x74, 0x61, 0x74, 0x73, 0x12, 0x17, 0x2e, 0x66,
	0x69, 0x6c, 0x65, 0x73, 0x63, 0x61, 0x6e, 0x73, 0x74, 0x61, 0x74, 0x2e, 0x46, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x63, 0x61, 0x6e,
	0x73, 0x74, 0x61, 0x74, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x53, 0x74, 0x61, 0x74, 0x73, 0x22,
	0x00, 0x30, 0x01, 0x12, 0x4a, 0x0a, 0x07, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x12, 0x1c,
	0x2e, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x63, 0x61, 0x6e, 0x73, 0x74, 0x61, 0x74, 0x2e, 0x54, 0x72,
	0x69, 0x67, 0x67, 0x65, 0x72, 0x42, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x1a, 0x1f, 0x2e, 0x66,
	0x69, 0x6c, 0x65, 0x73, 0x63, 0x61, 0x6e, 0x73, 0x74, 0x61, 0x74, 0x2e, 0x54, 0x72, 0x69, 0x67,
	0x67, 0x65, 0x72, 0x42, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x22, 0x00, 0x42,
	0x1d, 0x5a, 0x1b, 0x73, 0x63, 0x61, 0x6e, 0x66, 0x69, 0x6c, 0x65, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x73, 0x63, 0x61, 0x6e, 0x66, 0x69, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_file_scan_stat_proto_rawDescOnce sync.Once
	file_file_scan_stat_proto_rawDescData = file_file_scan_stat_proto_rawDesc
)

func file_file_scan_stat_proto_rawDescGZIP() []byte {
	file_file_scan_stat_proto_rawDescOnce.Do(func() {
		file_file_scan_stat_proto_rawDescData = protoimpl.X.CompressGZIP(file_file_scan_stat_proto_rawDescData)
	})
	return file_file_scan_stat_proto_rawDescData
}

var file_file_scan_stat_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_file_scan_stat_proto_goTypes = []interface{}{
	(*TriggerBackend)(nil),    // 0: filescanstat.TriggerBackend
	(*TriggerBackendRes)(nil), // 1: filescanstat.TriggerBackendRes
	(*Word)(nil),              // 2: filescanstat.Word
	(*File)(nil),              // 3: filescanstat.File
	(*FilesStats)(nil),        // 4: filescanstat.FilesStats
	(*FsRequest)(nil),         // 5: filescanstat.FsRequest
}
var file_file_scan_stat_proto_depIdxs = []int32{
	3, // 0: filescanstat.FilesStats.file:type_name -> filescanstat.File
	2, // 1: filescanstat.FilesStats.words:type_name -> filescanstat.Word
	5, // 2: filescanstat.ScanStatService.GetFilesStats:input_type -> filescanstat.FsRequest
	0, // 3: filescanstat.ScanStatService.Process:input_type -> filescanstat.TriggerBackend
	4, // 4: filescanstat.ScanStatService.GetFilesStats:output_type -> filescanstat.FilesStats
	1, // 5: filescanstat.ScanStatService.Process:output_type -> filescanstat.TriggerBackendRes
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_file_scan_stat_proto_init() }
func file_file_scan_stat_proto_init() {
	if File_file_scan_stat_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_file_scan_stat_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TriggerBackend); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_file_scan_stat_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TriggerBackendRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_file_scan_stat_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Word); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_file_scan_stat_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*File); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_file_scan_stat_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FilesStats); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_file_scan_stat_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_file_scan_stat_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_file_scan_stat_proto_goTypes,
		DependencyIndexes: file_file_scan_stat_proto_depIdxs,
		MessageInfos:      file_file_scan_stat_proto_msgTypes,
	}.Build()
	File_file_scan_stat_proto = out.File
	file_file_scan_stat_proto_rawDesc = nil
	file_file_scan_stat_proto_goTypes = nil
	file_file_scan_stat_proto_depIdxs = nil
}
